<?php 
        // Variables y constantes globales que se usan en el sistema
        // require "config.php";

        $cabecerag = "
        SELECT 'IDADMINISTRADORA' AS CAMPO, 'IDADMINISTRADORA' AS DESCCAMPO
        UNION ALL
        SELECT 'RAZONSOCIAL' AS CAMPO,'EPS' AS DESCCAMPO
        UNION ALL 
        SELECT 'TIPO_DOC' AS CAMPO, 'TIPO_DOC' AS DESCCAMPO
        UNION ALL
        SELECT 'IDAFILIADO' AS CAMPO, 'IDAFILIADO' AS DESCCAMPO
        UNION ALL
        SELECT 'PNOMBRE' AS CAMPO, 'PNOMBRE' AS DESCCAMPO
        UNION ALL
        SELECT 'SNOMBRE' AS CAMPO, 'SNOMBRE' AS DESCCAMPO
        UNION ALL
        SELECT 'PAPELLIDO' AS CAMPO, 'PAPELLIDO' AS DESCCAMPO
        UNION ALL
        SELECT 'SAPELLIDO' AS CAMPO, 'SAPELLIDO' AS DESCCAMPO
        UNION ALL
        SELECT 'FNACIMIENTO' AS CAMPO, 'FNACIMIENTO' AS DESCCAMPO
        UNION ALL
        SELECT 'EDAD' AS CAMPO, 'EDAD' AS DESCCAMPO
        UNION ALL
        SELECT 'SEXO' AS CAMPO, 'SEXO' AS DESCCAMPO
        UNION ALL
        SELECT 'DIRECCION' AS CAMPO, 'DIRECCION' AS DESCCAMPO
        UNION ALL
        SELECT 'TELEFONORES' AS CAMPO, 'TELEFONO' AS DESCCAMPO
        UNION ALL
        SELECT 'GRUPOETNICO' AS CAMPO, 'GRUPOETNICO' AS DESCCAMPO
        UNION ALL
        SELECT 'TIPODISCAPACIDAD' AS CAMPO, 'TIPODISCAPACIDAD' AS DESCCAMPO
        UNION ALL
        SELECT 'ESTADOCIVIL' AS CAMPO, 'ESTADOCIVIL' AS DESCCAMPO
        UNION ALL
        SELECT 'IDESCOLARIDAD' AS CAMPO, 'IDESCOLARIDAD' AS DESCCAMPO
        UNION ALL
        SELECT 'OCUPACIONC' AS CAMPO, 'OCUPACIONC' AS DESCCAMPO
        UNION ALL
        SELECT 'CONSECUTIVO' AS CAMPO, 'CONSECUTIVO' AS DESCCAMPO
        UNION ALL
        SELECT 'IDSEDE' AS CAMPO, 'IDSEDE' AS DESCCAMPO
        UNION ALL
        SELECT 'SEDECAB' AS CAMPO, 'SEDECAB' AS DESCCAMPO
        UNION ALL
        SELECT 'FECHA_HC' AS CAMPO, 'FECHA_HC' AS DESCCAMPO
        UNION ALL
        SELECT 'CLASEPLANTILLA' AS CAMPO, 'CLASEPLANTILLA' AS DESCCAMPO
        UNION ALL
        SELECT 'TIPO_USUARIO' AS CAMPO, 'TIPO_USUARIO' AS DESCCAMPO
        UNION ALL
        SELECT 'ESPECIALIDADM' AS CAMPO, 'ESPECIALIDADM' AS DESCCAMPO
        UNION ALL
        SELECT 'IDMEDICO' AS CAMPO, 'IDMEDICO' AS DESCCAMPO
        UNION ALL
        SELECT 'MEDICO' AS CAMPO, 'MEDICO' AS DESCCAMPO
        UNION ALL
        SELECT 'TIPODX' AS CAMPO, 'TIPODX' AS DESCCAMPO
        UNION ALL
        SELECT 'IDDX' AS CAMPO, 'IDDX' AS DESCCAMPO
        UNION ALL
        SELECT 'DX1' AS CAMPO, 'DX1' AS DESCCAMPO
        UNION ALL
        SELECT 'DX2' AS CAMPO, 'DX2' AS DESCCAMPO
        UNION ALL
        SELECT 'DX3' AS CAMPO, 'DX3' AS DESCCAMPO";

        // CARACTERES DE ESCAPE PARA REEMPLZAR Y EVITAR ERRORES AL MOMENTO DE GENERAR EL ARCHIVO DE EXCEL
        // '/`/', '/#/', '/%/', '/>/', '/</', '/!/', '/./', '/[ -]+/', '/]/', '/\*/', '/\$/', '/;/', '/:/', '/\?/', '/\^/', '/{/', '/}/', '/\/', '/=/', '/"/', '/\'/'
        // prenatal_evo_rpt.php
        // $activeSheet->setCellValueByColumnAndRow($x,$y,preg_replace($caracteres1, ' ', $dato));

        $caracteres1 = array('/\s\s+/','/-/','/\+/','/=/');
        $caracteres2 = array('/--/','/\+\+/','/==/','/=/');

?>
