<?php
// Require composer autoload
require_once __DIR__ . '/vendor/autoload.php';
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
$spreadsheet = new Spreadsheet();  /*----Spreadsheet object-----*/
$Excel_writer = new Xlsx($spreadsheet);  /*----- Excel (Xls) Object*/
$spreadsheet->setActiveSheetIndex(0);
$activeSheet = $spreadsheet->getActiveSheet();


require_once('database.class.php');
$conn = new Database();
// Create an instance of the class:
//$mpdf = new \Mpdf\Mpdf();
//$mpdf->setFooter('{PAGENO}');

$parts = explode('-', $_POST['fechaini']);
$fechaini  = $parts[2].'/'.$parts[1].'/'.$parts[0];

$parts = explode('-', $_POST['fechafin']);
$fechafin  = $parts[2].'/'.$parts[1].'/'.$parts[0];

$fechaini.=' 00:00:00.000';
$fechafin.=' 23:59:59.997';


$columnas=array("IDSEDE","SEDE","EPS","IDMEDICO","MEDICO","FECHA","IDAFILIADO","DOCIDAFILIADO","TIPO_DOC",
    "PAPELLIDO","SAPELLIDO","PNOMBRE","SNOMBRE","FNACIMIENTO","EDAD","CLASEPLANTILLA","IDDX",
    "DIAGNOSTICO","REFERIRP","ESPECIAL");

$cabecera=array("IDSEDE","SEDE","EPS","IDMEDICO","MEDICO","FECHA","IDAFILIADO","DOCIDAFILIADO","TIPO_DOC",
    "PAPELLIDO","SAPELLIDO","PNOMBRE","SNOMBRE","FNACIMIENTO","EDAD","CLASEPLANTILLA","IDDX",
    "DIAGNOSTICO","REMITIDO","ESPECIALIDAD");
//$sth = $conn->prepare($cabecera);
//$sth->execute();
//$result = $sth->fetchall(PDO::FETCH_ASSOC);
$x=1;
$y=1;
/*while ($row = $sth->fetch())
{
    for($i=0;$i<count($columnas);$i++){
        //echo "<br>".$columnas[$i];
        //echo "<br>".$row[$columnas[$i]];
        $activeSheet->setCellValueByColumnAndRow($x,$y,$row[$columnas[$i]]);
        $x++;
    }
}*/
   for($i=0;$i<count($cabecera);$i++){
        //echo "<br>".$columnas[$i];
        //echo "<br>".$row[$columnas[$i]];
        $activeSheet->setCellValueByColumnAndRow($x,$y,$cabecera[$i]);
        $x++;
    }


$consulta="DECLARE @FECHAINI DATETIME='$fechaini';
DECLARE @FECHAFIN DATETIME='$fechafin';
SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO, CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='AIE02CE' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REFERIRP], [ESPECIAL])
	)as pvt 
	---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='HCCE' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALIDAD])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 
	---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='CRECIMTO' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPEC])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 



	---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='DTAJOVEN' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITI], [ESPECILAIDAD])  ---- CAMPOS DE PESO Y TALLA               ------------IN ([PESO],[TALLA])
	)as pvt 

---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='DTAMSANO' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITI], [ESPECIALI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='HCDBTW' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 


---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='EVOPRECO' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMIT], [ESPECI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 



---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='AIEMBCE' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REFERIRP], [ESPEC])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX 
			WHERE b.CLASEPLANTILLA='HCDBTCO' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALID])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='HCHTA' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

	---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='HCHTACO' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='HCHTADBT' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='HCPRECCE' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMIT], [ESPECI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX 
			WHERE b.CLASEPLANTILLA='HTADBTCO' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECLI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX 
			WHERE b.CLASEPLANTILLA='PLANIFIC' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPEC])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='PRECONPV' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMIT], [ESPECI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='REVAYU' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALIDAD])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 


---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='REVJOV' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------

UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='AIEP25CE' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPEC])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 


---------------------------------------------------------------------

UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX 
			WHERE b.CLASEPLANTILLA='AIEPRNCE' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REFERIRP], [ESPECIAL])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 


---------------------------------------------------------------------
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='CASENO' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

	
---------------------------------------------------------------------
UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX  
			WHERE b.CLASEPLANTILLA='HAGUDEZA' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMIOFT], [ESPECIALIDAD])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

---------------------------------------------------------------------
UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX 
			WHERE b.CLASEPLANTILLA='HCPSICO' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIAL])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

	
---------------------------------------------------------------------
UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX  
			WHERE b.CLASEPLANTILLA='HCTSOCIA' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALI])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

	

---------------------------------------------------------------------
UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX 
			WHERE b.CLASEPLANTILLA='PROCDIU' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITI], [ESPECIAL])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 
	
---------------------------------------------------------------------
UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX
			WHERE b.CLASEPLANTILLA='PUERPER' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALIDAD])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 
	
---------------------------------------------------------------------
UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX 
			WHERE b.CLASEPLANTILLA='REVMSA' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO], [ESPECIALIDAD])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt 

	
	UNION ALL
	SELECT *
	FROM (
		SELECT
			b.IDSEDE,s.DESCRIPCION AS SEDE,t.RAZONSOCIAL as EPS,
			b.IDMEDICO, d.NOMBRE AS MEDICO,CONVERT(VARCHAR(10),b.FECHA,103) as FECHA,
			c.IDAFILIADO, c.DOCIDAFILIADO, c.TIPO_DOC,
			c.PAPELLIDO,c.SAPELLIDO,c.PNOMBRE, COALESCE(c.SNOMBRE,'') AS SNOMBRE,
			CONVERT(VARCHAR(10),c.FNACIMIENTO,103) AS FNACIMIENTO,
			dbo.fna_EdadenMeses(c.FNACIMIENTO,b.FECHA) AS EDAD,
			a.CAMPO AS [CAMPO], coalesce(a.ALFANUMERICO,'') AS VALOR, b.CLASEPLANTILLA,
			b.IDDX, M.DESCRIPCION AS DIAGNOSTICO
		FROM
			HCA b INNER JOIN HCAD a on a.CONSECUTIVO=b.CONSECUTIVO
			INNER JOIN AFI c ON c.IDAFILIADO=b.IDAFILIADO 
			INNER JOIN MED d on d.IDMEDICO=b.IDMEDICO
			LEFT JOIN SED s on s.IDSEDE=b.IDSEDE 
			LEFT JOIN TER t on t.IDTERCERO=c.IDADMINISTRADORA
			LEFT JOIN MDX m on m.IDDX=b.IDDX 
			WHERE b.CLASEPLANTILLA='HCTSOCIS' AND b.FECHA BETWEEN @FECHAINI AND @FECHAFIN
	) X
	PIVOT(
	MIN(VALOR) 
	FOR [CAMPO] IN ([REMITIDO],[ ])  ---- CAMPOS DE PESO Y TALLA 
	)as pvt ";

$sth = $conn->prepare($consulta);
$sth->execute();
//$result = $sth->fetchall(PDO::FETCH_ASSOC);
$x=1;
$y=2;
while ($row = $sth->fetch())
{
    for($i=0;$i<count($columnas);$i++){
        //echo "<br>".$columnas[$i];
        //echo "<br>".$row[$columnas[$i]];
        $activeSheet->setCellValueByColumnAndRow($x,$y,$row[$columnas[$i]]);
        $x++;
    }
    $x=1;
    $y++;
    //echo $row['name'] . "\n";
}
/*foreach($result as $key=>$row) {
    foreach($row as $key2=>$row2){

        $activeSheet->setCellValueByColumnAndRow($x,$y,$row2);
        $x++;
    }
    $y++;
    $x=1;
}*/

$filename='remisiones';
//$activeSheet->setCellValue('A1' , 'New file content')->getStyle('A1')->getFont()->setBold(true);
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment;filename="'. $filename .'.xlsx"'); /*-- $filename is  xsl filename ---*/
header('Cache-Control: max-age=0');
$Excel_writer->save('php://output');
exit;